## Import Packages

In [4]:
import numpy as np
import pandas as pd

# 1. Array (Numpy)

### 1-1. Creation of Array Data

#### 1-1-1. Define Array Data by Assigning Values

- One-dimensional data (vector)

In [5]:
array_1d = np.array([0,1,2])
array_1d

array([0, 1, 2])

"Numerical operations on array data are performed on each element of the array"

-> Very efficient in data analysis

In [6]:
# List (basic data structures in Python)

a = [1,2,3]
b = [3,3,3]

a+b

[1, 2, 3, 3, 3, 3]

In [7]:
# Array (numpy)

a = np.array([1,2,3]) # convert 'list' data into 'array' data
b = np.array([3,3,3])

a+b

array([4, 5, 6])

* Two-dimensional data (matrix)

In [8]:
array_2d = np.array([[10,11,12],[20,21,22]])
array_2d

array([[10, 11, 12],
       [20, 21, 22]])

* Three-dimensional data

In [9]:
array_3d = np.array([ [[10,11,12],[20,21,22]] , [[100,111,112],[120,121,122]] ])
array_3d

array([[[ 10,  11,  12],
        [ 20,  21,  22]],

       [[100, 111, 112],
        [120, 121, 122]]])

#### 1-1-2. Generate Array Data Filled with 0 or 1

In [10]:
ary_01 = np.zeros(5)
ary_01

array([0., 0., 0., 0., 0.])

In [11]:
ary_02 = np.zeros((2,3))
ary_02

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ary_11 = np.ones(5)
ary_11

array([1., 1., 1., 1., 1.])

In [13]:
ary_12 = np.ones((2,3))
ary_12

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 1-1-3. Generate Array Data by Designating a Range

np.arange(a) : Generate an array greater than or equal to 0 and less than 'a'

In [14]:
ary_range_1 = np.arange(5)
ary_range_1

array([0, 1, 2, 3, 4])

np.arange(a,b) : Generate an array greater than or equal to 'a' and less than 'b'

In [15]:
ary_range_2 = np.arange(1,10)
ary_range_2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(a,b,c) : Generate an array greater than or equal to 'a' and less than 'b' with an interval 'c'

In [16]:
ary_range_3 = np.arange(1,10,0.5)
ary_range_3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

#### Range Definition of Basic Python

range(a) : Generate a range greater than or equal to 0 and less than 'a'
* It is not an array data. (mainly applying it for loops)

In [17]:
range_1 = range(5)
range_1

range(0, 5)

range(a,b) : Generate a range greater than or equal to 'a' and less than 'b'

In [18]:
range_2 = range(1,10)
range_2

range(1, 10)

### 1-2. Array Data Indexing

#### 1-2-1. Extract a value from a specific position

In [19]:
ary_1d = np.arange(1,10)
ary_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ary_1d[0]

np.int64(1)

In [21]:
ary_2d = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
ary_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
ary_2d[0][0]

np.int64(1)

#### 1-2-2. Extract values from specific range

In [23]:
ary_1d[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
ary_2d[1][0:2]

array([4, 5])

# 2. Data Frame (Pandas)

### 2-1. Creation of Data Frame
* Generally, DataFrame is defined by converting other data format

#### 2-1-1.  Define a DataFrame by Assigning Values

In [25]:
df_1 = pd.DataFrame([11,12,13])
df_1

    0
0  11
1  12
2  13

In [26]:
df_2 = pd.DataFrame({"A":['a','b','c'] , "B":[21,22,23] , "C":[31,32,33]})
df_2

   A   B   C
0  a  21  31
1  b  22  32
2  c  23  33

#### 2-1-2. Generate a DataFrame by Converting an Array Data

In [27]:
ary_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
df_3 = pd.DataFrame(ary_2d)
df_3

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### 2-2. Data Frame Indexing

In [29]:
df_3.iloc[:2 , 0:3]

   0  1  2
0  1  2  3
1  4  5  6